### ISSUE TITLE
/bin/bash: /start.sh: No such file or directory

### ISSUE THREAD

**Issue by Sameeranjoshi** [plainerman/qemuriscv#1]
```
root@5c4c9da5f014:/# /bin/bash /start.sh
/bin/bash: /start.sh: No such file or directory
```
```
uname -a
Linux 5c4c9da5f014 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by plainerman** [comment]
I believe, you are looking for the Fedora image emulating RISC-V running in docker, as I have not updated the description of this repository.

This repository has been modified, to only provide a compiled gcc, allowing to generate RISC-V assembly and a qemu-riscv (64bit) emulator. (gcc should be in /opt/riscv)

If you are looking for the fedora Dockerfile, it is still available here:
https://github.com/plainerman/qemuriscv/tree/master/fedora

~~But you have to build the docker image yourself.~~ Username is `root`, password is `riscv`.

If you have any further questions, please reopen this issue.
Have a nice day.

**Comment by plainerman** [comment]
I have built the fedora image and it will be available soon via plainerman/qemuriscv:fedora
Running the image will be the same as it used to be:

`docker run -it plainerman/qemuriscv:fedora /bin/bash`
`bash /start.sh`
Username is `root`, password is `riscv`.
